export type EmailJobName =
  | 'welcome'
  | 'application_submitted'
  | 'application_approved'
  | 'application_rejected'
  | 'application_interview_scheduled'
  | 'payment_reminder'
  | 'verification_approved'
  | 'verification_rejected'
  | 'provisionary_followup_t2'
  | 'provisionary_followup_t5'
  | 'provisionary_followup_t10'
  | 'account_setup'
  | 'forgot_password'
  | 'mentorship_request_received'
  | 'mentorship_request_accepted'
  | 'mentorship_request_rejected'
  | 'mentorship_reminder'
  | 'mentorship_reschedule_proposed'
  | 'mentorship_reschedule_accepted'
  | 'mentorship_reschedule_rejected'
  | 'weekly_digest'
  | 'payment_confirmed'
  | 'membership_paused'
  | 'membership_reactivated'
  | 'mentor_profile_approved'
  | 'membership_activated'
  | 'membership_renewal_reminder_30'
  | 'membership_renewal_reminder_7'
  | 'membership_renewal_reminder_1'
  | 'membership_expired'
  | 'application_under_review'
  | 'application_interview_invitation'
  | 'application_interview_confirmed'
  | 'application_interview_rescheduled'
  | 'application_sla_alert'
  | 'payment_waived'
  | 'feedback_received'
  | 'feedback_reviewing'
  | 'feedback_in_progress'
  | 'feedback_awaiting_info'
  | 'feedback_mentoring'
  | 'feedback_partner_referred'
  | 'feedback_education_suggested'
  | 'feedback_resolved'
  | 'feedback_satisfaction_request'
  | 'dm_received'
  | 'admin_broadcast'
  | 'level_up'
  | 'event_reminder_24h'
  | 'event_reminder_1h'
  | 'event_invitation'
  | 'event_ticket'
  | 'event_cancellation'
  | 'event_waitlist_available'
  | 'course_certificate_issued'
  | 'course_completed'
  | 'course_announcement'
  | 'course_payment_confirmed'
  | 'course_payment_rejected'
  | 'store_order_confirmed'
  | 'store_order_processing'
  | 'store_order_shipped'
  | 'store_order_delivered'
  | 'store_order_cancelled'
  | 'store_seller_approved'
  | 'store_seller_rejected'
  | 'store_digital_download'
  | 'store_abandoned_cart'
  | 'store_abandoned_cart_24h'
  | 'store_abandoned_cart_72h'
  | 'store_gift_card'
  | 'store_payout_released'
  | 'store_payout_paid'
  | 'store_review_request'
  | 'store_stock_available'
  | 'listing_contact'
  | 'listing_expiry_reminder'
  | 'listing_alert_new'
  | 'newsletter_confirm'
  | 'otp_verification'
  | 'comment_verify'
  | 'test_certificate'
  | 'survey_participated'
  | 'competition_result_winner'
  | 'library_regulation_update';

export interface EmailAttachment {
  name: string;
  content: string; // base64
  type: string;    // mime type
}

export interface EmailJob {
  to: string;
  name: EmailJobName;
  variables: Record<string, string | number | boolean>;
  attachments?: EmailAttachment[];
}
