-- 1. Delete Cansu Erdogan and Ozan Kurt from mentee pool
DELETE FROM mentee_applications WHERE name IN ('Cansu Erdoğan', 'Ozan Kurt');

-- 2. Insert approved mentor profiles for 6 members
INSERT INTO mentor_profiles (id, user_id, expertise_areas, bio, session_format, city, monthly_capacity, is_accepting_requests, completed_session_count, admin_status, session_duration_min, session_duration_max, capacity_type, periodic_capacity, created_at, updated_at) VALUES
  (gen_random_uuid(), '965668a9-e893-431c-a467-8d56b6ec01d2', ARRAY['cbs_gis','uzaktan_algilama','yazilim_teknoloji'], '8 yillik CBS ve uzaktan algilama deneyimim var. QGIS, ArcGIS ve Python ile cesitli projelerde calistim.', 'online', 'İstanbul', 3, true, 3, 'approved', 45, 60, 'both', 2, NOW(), NOW()),
  (gen_random_uuid(), '5704baf8-27ac-47e8-a70b-b37ec4b2eb1c', ARRAY['kadastro','insaat_olcmesi','deniz_hidrografi'], 'Kadastro, olcme ve hidrografi konularinda TKGM deneyimiyle mentorluk yapiyorum.', 'online', 'Ankara', 4, true, 5, 'approved', 60, 90, 'monthly', 0, NOW(), NOW()),
  (gen_random_uuid(), '0d7d08ea-0887-478d-8c8c-144122e7855f', ARRAY['fotogrametri','lidar_nokta_bulutu','uzaktan_algilama'], 'Fotogrametri ve LiDAR konusunda uzmanim. Drone tabanli projelerde rehberlik edebilirim.', 'both', 'İzmir', 2, true, 2, 'approved', 60, 90, 'both', 1, NOW(), NOW()),
  (gen_random_uuid(), '227dfcd0-46ab-48b6-ab25-aa279d63db64', ARRAY['kadastro','gayrimenkul'], 'Kadastro muhendisi. Parselasyon ve tapu islemleri konusunda tecrübeliyim.', 'in_person', 'Bursa', 2, true, 1, 'approved', 45, 60, 'monthly', 0, NOW(), NOW()),
  (gen_random_uuid(), '6c2b632c-3912-4517-a8a6-26398ab6e5ff', ARRAY['akademik_arastirma','kariyer_danismanligi','cbs_gis'], 'Ogretim gorevlisi olarak kariyer ve akademik arastirma konularinda rehberlik ediyorum.', 'online', 'Erzurum', 0, true, 7, 'approved', 60, 90, 'periodic', 3, NOW(), NOW()),
  (gen_random_uuid(), 'f2d0dff8-35ca-4e69-8903-2a8b0d88e40a', ARRAY['kariyer_danismanligi','girisimcilik'], 'Is gelistirme ve kariyer yonetimi konularinda kurumsal deneyimle mentorluk yapiyorum.', 'online', 'İstanbul', 2, true, 0, 'approved', 30, 60, 'both', 2, NOW(), NOW());

-- 3. Insert mentee applications for 6 members
INSERT INTO mentee_applications (id, user_id, name, email, topic, goal, preferred_format, source, status, engagement_type, created_at) VALUES
  (gen_random_uuid(), 'b7abd8a9-bf06-4039-bae1-12231f1d6dc4', 'Asli Korkmaz', 'asli.korkmaz@outlook.com', 'CBS ve uzaktan algilama kariyeri', 'QGIS ve Python ile uzaktan algilama projeleri gelistirmek istiyorum. Uydu goruntu isleme ve CBS analizi konusunda kariyer hedeflerim var.', 'online', 'mutfak', 'pending', 'single_session', NOW()),
  (gen_random_uuid(), 'e51e0bc5-3f39-4321-900c-4079038492d0', 'Can Yildiz', 'can.yildiz@ktu.edu.tr', 'Deniz haritaciligi ve GNSS kariyer rehberligi', 'Hidrografi ve deniz haritaciligi alaninda kariyer yapmak istiyorum. GNSS olcmeleri ve deniz surveying konusunda pratik rehberligi ihtiyacim var.', 'online', 'mutfak', 'pending', 'single_session', NOW()),
  (gen_random_uuid(), '1acdae65-a6f0-45eb-9731-767eee2d793b', 'Deniz Cetin', 'deniz.cetin@gmail.com', 'Web CBS ve acik kaynak GIS teknolojileri', 'QGIS, GeoServer ve Leaflet.js ile web harita uygulamalari gelistiriyorum. Bu alanda uzmanlasmak ve is bulmak icin donemlik mentorluk ariyorum.', 'online', 'mutfak', 'pending', 'periodic', NOW()),
  (gen_random_uuid(), 'dbaaba0f-44d3-4f61-8678-5f3894e7b449', 'Ece Gunes', 'ece.gunes@eskisehir.edu.tr', 'CBS kariyeri ve Python scripting', 'QGIS ve Python kullanarak CBS alaninda is hayatina hazirlanmak istiyorum. Portfoy olusturma ve is basvurulari hakkinda rehberlik ariyorum.', 'online', 'mutfak', 'pending', 'single_session', NOW()),
  (gen_random_uuid(), 'b160a47a-0a76-424a-b198-d79f751fcae4', 'Alp Kilic', 'alp.kilic@omu.edu.tr', 'Harita muhendisligi kariyer danismanligi', 'Mezuniyet sonrasi kariyer seceneklerini ogrenip sektorun firsatlarini kesmek istiyorum. Kariyer danismanligi ve yonlendirme almak istiyorum.', 'online', 'mutfak', 'pending', 'single_session', NOW()),
  (gen_random_uuid(), 'a8c4597a-9acb-451d-92cb-8708a2dc0fc1', 'Merve Dogan', 'merve.dogan@cukurova.edu.tr', 'QGIS uzmanlaşma ve fotogrametri/drone egitimi', 'QGIS ile veri analizi ve fotogrametri alanlarinda uzmanlasmak istiyorum. Drone operasyonlari ve goruntu isleme konusunda donemlik mentorluk ariyorum.', 'online', 'mutfak', 'pending', 'periodic', NOW());
