export const ILLER: string[] = [
  'Adana', 'Adıyaman', 'Afyonkarahisar', 'Ağrı', 'Aksaray',
  'Amasya', 'Ankara', 'Antalya', 'Ardahan', 'Artvin',
  'Aydın', 'Balıkesir', 'Bartın', 'Batman', 'Bayburt',
  'Bilecik', 'Bingöl', 'Bitlis', 'Bolu', 'Burdur',
  'Bursa', 'Çanakkale', 'Çankırı', 'Çorum', 'Denizli',
  'Diyarbakır', 'Düzce', 'Edirne', 'Elazığ', 'Erzincan',
  'Erzurum', 'Eskişehir', 'Gaziantep', 'Giresun', 'Gümüşhane',
  'Hakkari', 'Hatay', 'Iğdır', 'Isparta', 'İstanbul',
  'İzmir', 'Kahramanmaraş', 'Karabük', 'Karaman', 'Kars',
  'Kastamonu', 'Kayseri', 'Kilis', 'Kırıkkale', 'Kırklareli',
  'Kırşehir', 'Kocaeli', 'Konya', 'Kütahya', 'Malatya',
  'Manisa', 'Mardin', 'Mersin', 'Muğla', 'Muş',
  'Nevşehir', 'Niğde', 'Ordu', 'Osmaniye', 'Rize',
  'Sakarya', 'Samsun', 'Siirt', 'Sinop', 'Sivas',
  'Şanlıurfa', 'Şırnak', 'Tekirdağ', 'Tokat', 'Trabzon',
  'Tunceli', 'Uşak', 'Van', 'Yalova', 'Yozgat',
  'Zonguldak',
];

// Tüm Meslek Yüksekokulları — kaynak: kunfeyekun.org (526 okul)
export const MYOLAR: string[] = [
  'Abant İzzet Baysal Üniversitesi Bolu Meslek Yüksekokulu',
  'Abant İzzet Baysal Üniversitesi Gerede Meslek Yüksekokulu',
  'Abant İzzet Baysal Üniversitesi Mengen Meslek Yüksekokulu',
  'Abant İzzet Baysal Üniversitesi Mudurnu Süreyya Astarcı Meslek Yüksekokulu',
  'Adıyaman Üniversitesi Besni Meslek Yüksekokulu',
  'Adıyaman Üniversitesi Gölbaşı Meslek Yüksekokulu',
  'Adıyaman Üniversitesi Kahta Meslek Yüksekokulu',
  'Adıyaman Üniversitesi Meslek Yüksekokulu',
  'Adıyaman Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Adnan Menderes Üniversitesi Aydın Meslek Yüksekokulu',
  'Adnan Menderes Üniversitesi Aydın Sağlık Hizmetleri Meslek Yüksekokulu',
  'Adnan Menderes Üniversitesi Bozdoğan Meslek Yüksekokulu',
  'Adnan Menderes Üniversitesi Çine Meslek Yüksekokulu',
  'Adnan Menderes Üniversitesi Didim Meslek Yüksekokulu',
  'Adnan Menderes Üniversitesi Karacasu Memnune İnci Meslek Yüksekokulu',
  'Adnan Menderes Üniversitesi Koçarlı Meslek Yüksekokulu',
  'Adnan Menderes Üniversitesi Kuyucak Meslek Yüksekokulu',
  'Adnan Menderes Üniversitesi Nazilli Meslek Yüksekokulu',
  'Adnan Menderes Üniversitesi Söke Meslek Yüksekokulu',
  'Adnan Menderes Üniversitesi Sultanhisar Meslek Yüksekokulu',
  'Adnan Menderes Üniversitesi Yenipazar Meslek Yüksekokulu',
  'Afyon Kocatepe Üniversitesi Afyon Meslek Yüksekokulu',
  'Afyon Kocatepe Üniversitesi Atatürk Sağlık Hizmetleri Meslek Yüksekokulu',
  'Afyon Kocatepe Üniversitesi Başmakçı Meslek Yüksekokulu',
  'Afyon Kocatepe Üniversitesi Bayat Meslek Yüksekokulu',
  'Afyon Kocatepe Üniversitesi Bolvadin Meslek Yüksekokulu',
  'Afyon Kocatepe Üniversitesi Çay Meslek Yüksekokulu',
  'Afyon Kocatepe Üniversitesi Dazkırı Meslek Yüksekokulu',
  'Afyon Kocatepe Üniversitesi Dinar Meslek Yüksekokulu',
  'Afyon Kocatepe Üniversitesi Emirdağ Meslek Yüksekokulu',
  'Afyon Kocatepe Üniversitesi İscehisar Meslek Yüksekokulu',
  'Afyon Kocatepe Üniversitesi Sandıklı Meslek Yüksekokulu',
  'Afyon Kocatepe Üniversitesi Sinanpaşa Meslek Yüksekokulu',
  'Afyon Kocatepe Üniversitesi Sultandağı Meslek Yüksekokulu',
  'Afyon Kocatepe Üniversitesi Şuhut Meslek Yüksekokulu',
  'Afyon Kocatepe Üniversitesi Uzaktan Eğitim Meslek Yüksekokulu',
  'Ahi Evran Üniversitesi Çiçekdağı Meslek Yüksekokulu',
  'Ahi Evran Üniversitesi Kaman Meslek Yüksekokulu',
  'Ahi Evran Üniversitesi Kırşehir Meslek Yüksekokulu',
  'Ahi Evran Üniversitesi Mucur Meslek Yüksekokulu',
  'Akdeniz Üniversitesi Akseki Meslek Yüksekokulu',
  'Akdeniz Üniversitesi Alanya Meslek Yüksekokulu',
  'Akdeniz Üniversitesi Elmalı Meslek Yüksekokulu',
  'Akdeniz Üniversitesi Finike Meslek Yüksekokulu',
  'Akdeniz Üniversitesi Korkuteli Meslek Yüksekokulu',
  'Akdeniz Üniversitesi Kumluca Meslek Yüksekokulu',
  'Akdeniz Üniversitesi Manavgat Meslek Yüksekokulu',
  'Akdeniz Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Akdeniz Üniversitesi Serik Meslek Yüksekokulu',
  'Akdeniz Üniversitesi Sosyal Bilimler Meslek Yüksekokulu',
  'Akdeniz Üniversitesi Teknik Bilimler Meslek Yüksekokulu',
  'Aksaray Üniversitesi Berat Cömertoğlu Meslek Yüksekokulu',
  'Aksaray Üniversitesi Güzelyurt Meslek Yüksekokulu',
  'Aksaray Üniversitesi Meslek Yüksekokulu',
  'Aksaray Üniversitesi Ortaköy Meslek Yüksekokulu',
  'Aksaray Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Amasya Üniversitesi Merzifon Meslek Yüksekokulu',
  'Amasya Üniversitesi Meslek Yüksekokulu',
  'Anadolu Üniversitesi Eskişehir Meslek Yüksekokulu',
  'Anadolu Üniversitesi Porsuk Meslek Yüksekokulu',
  'Anadolu Üniversitesi Yunus Emre Meslek Yüksekokulu',
  'Ankara Üniversitesi Adalet Meslek Yüksekokulu',
  'Ankara Üniversitesi Başkent Meslek Yüksekokulu',
  'Ankara Üniversitesi Beypazarı Meslek Yüksekokulu',
  'Ankara Üniversitesi Elmadağ Meslek Yüksekokulu',
  'Ankara Üniversitesi Kalecik Meslek Yüksekokulu',
  'Ankara Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Atatürk Üniversitesi Aşkale Meslek Yüksekokulu',
  'Atatürk Üniversitesi Erzurum Meslek Yüksekokulu',
  'Atatürk Üniversitesi Hınıs Meslek Yüksekokulu',
  'Atatürk Üniversitesi İspir Hamza Polat Meslek Yüksekokulu',
  'Atatürk Üniversitesi Narman Meslek Yüksekokulu',
  'Atatürk Üniversitesi Oltu Meslek Yüksekokulu',
  'Atatürk Üniversitesi Pasinler Meslek Yüksekokulu',
  'Atatürk Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Bahçeşehir Üniversitesi Meslek Yüksekokulu',
  'Balıkesir Üniversitesi Altınoluk Meslek Yüksekokulu',
  'Balıkesir Üniversitesi Ayvalık Meslek Yüksekokulu',
  'Balıkesir Üniversitesi Balıkesir Meslek Yüksekokulu',
  'Balıkesir Üniversitesi Bandırma Meslek Yüksekokulu',
  'Balıkesir Üniversitesi Bigadiç Meslek Yüksekokulu',
  'Balıkesir Üniversitesi Burhaniye Meslek Yüksekokulu',
  'Balıkesir Üniversitesi Dursunbey Meslek Yüksekokulu',
  'Balıkesir Üniversitesi Edremit Meslek Yüksekokulu',
  'Balıkesir Üniversitesi Erdek Meslek Yüksekokulu',
  'Balıkesir Üniversitesi Gönen Meslek Yüksekokulu',
  'Balıkesir Üniversitesi Havran Meslek Yüksekokulu',
  'Balıkesir Üniversitesi İvrindi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Balıkesir Üniversitesi Savaştepe Meslek Yüksekokulu',
  'Balıkesir Üniversitesi Sındırgı Meslek Yüksekokulu',
  'Balıkesir Üniversitesi Susurluk Meslek Yüksekokulu',
  'Bartın Üniversitesi Bartın Meslek Yüksekokulu',
  'Başkent Üniversitesi Adana Sağlık Hizmetleri Meslek Yüksekokulu',
  'Başkent Üniversitesi Kazan Meslek Yüksekokulu',
  'Başkent Üniversitesi Konya Sağlık Hizmetleri Meslek Yüksekokulu',
  'Başkent Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Başkent Üniversitesi Sosyal Bilimler Meslek Yüksekokulu',
  'Başkent Üniversitesi Teknik Bilimler Meslek Yüksekokulu',
  'Başkent Üniversitesi Turizm Ve Otelcilik Meslek Yüksekokulu',
  'Adnan Menderes Üniversitesi Atça Meslek Yüksekokulu',
  'Beykent Üniversitesi Meslek Yüksekokulu',
  'Bilecik Üniversitesi Bozüyük Meslek Yüksekokulu',
  'Bilecik Üniversitesi Gölpazarı Meslek Yüksekokulu',
  'Bilecik Üniversitesi Meslek Yüksekokulu',
  'Bilecik Üniversitesi Osmaneli Meslek Yüksekokulu',
  'Bilecik Üniversitesi Pazaryeri Meslek Yüksekokulu',
  'Bilecik Üniversitesi Söğüt Meslek Yüksekokulu',
  'Bilkent Üniversitesi Bilgisayar Teknolojisi Ve Büro Yönetimi Meslek Yüksekokulu',
  'Bilkent Üniversitesi İngiliz Dili Meslek Yüksekokulu',
  'Boğaziçi Üniversitesi Otelcilik Meslek Yüksekokulu',
  'C.Ü Suşehri Timur Karabal Meslek Yüksekokulu',
  'C.Ü Şarkışla Aşık Veysel Meslek Yüksekokulu',
  'Celal Bayar Üniversitesi Ahmetli Meslek Yüksekokulu',
  'Celal Bayar Üniversitesi Akhisar Meslek Yüksekokulu',
  'Celal Bayar Üniversitesi Alaşehir Meslek Yüksekokulu',
  'Celal Bayar Üniversitesi Demirci Meslek Yüksekokulu',
  'Celal Bayar Üniversitesi Gölmarmara Meslek Yüksekokulu',
  'Celal Bayar Üniversitesi Gördes Meslek Yüksekokulu',
  'Celal Bayar Üniversitesi Kırkağaç Meslek Yüksekokulu',
  'Celal Bayar Üniversitesi Köprübaşı Meslek Yüksekokulu',
  'Celal Bayar Üniversitesi Kula Meslek Yüksekokulu',
  'Celal Bayar Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Celal Bayar Üniversitesi Salihli Meslek Yüksekokulu',
  'Celal Bayar Üniversitesi Sarıgöl Meslek Yüksekokulu',
  'Celal Bayar Üniversitesi Saruhanlı Meslek Yüksekokulu',
  'Celal Bayar Üniversitesi Soma Meslek Yüksekokulu',
  'Celal Bayar Üniversitesi Turgutlu Meslek Yüksekokulu',
  'Cumhuriyet Üniversitesi Cumhuriyet Meslek Yüksekokulu',
  'Cumhuriyet Üniversitesi Divriği Meslek Yüksekokulu',
  'Cumhuriyet Üniversitesi Gemerek Meslek Yüksekokulu',
  'Cumhuriyet Üniversitesi Gürün Meslek Yüksekokulu',
  'Cumhuriyet Üniversitesi Kangal Meslek Yüksekokulu',
  'Cumhuriyet Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Cumhuriyet Üniversitesi Sivas Meslek Yüksekokulu',
  'Cumhuriyet Üniversitesi Yıldızeli Meslek Yüksekokulu',
  'Cumhuriyet Üniversitesi Zara Meslek Yüksekokulu',
  'Çanakkale Onsekiz Mart Üniversitesi Ayvacık Meslek Yüksekokulu',
  'Çanakkale Onsekiz Mart Üniversitesi Bayramiç Meslek Yüksekokulu',
  'Çanakkale Onsekiz Mart Üniversitesi Biga Meslek Yüksekokulu',
  'Çanakkale Onsekiz Mart Üniversitesi Çan Meslek Yüksekokulu',
  'Çanakkale Onsekiz Mart Üniversitesi Çanakkale Meslek Yüksekokulu',
  'Çanakkale Onsekiz Mart Üniversitesi Ezine Meslek Yüksekokulu',
  'Çanakkale Onsekiz Mart Üniversitesi Gelibolu Piri Reis Meslek Yüksekokulu',
  'Çanakkale Onsekiz Mart Üniversitesi Gökçeada Meslek Yüksekokulu',
  'Çanakkale Onsekiz Mart Üniversitesi Lapseki Meslek Yüksekokulu',
  'Çanakkale Onsekiz Mart Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Çanakkale Onsekiz Mart Üniversitesi Yenice Meslek Yüksekokulu',
  'Çankaya Üniversitesi Çankaya Meslek Yüksekokulu',
  'Çankırı Karatekin Üniversitesi Meslek Yüksekokulu',
  'Çukurova Üniversitesi Adana Meslek Yüksekokulu',
  'Çukurova Üniversitesi Ceyhan Meslek Yüksekokulu',
  'Çukurova Üniversitesi Ceyhan Sağlık Hizmetleri Meslek Yüksekokulu',
  'Çukurova Üniversitesi Karaisalı Meslek Yüksekokulu',
  'Çukurova Üniversitesi Kozan Meslek Yüksekokulu',
  'Çukurova Üniversitesi Pozantı Meslek Yüksekokulu',
  'Çukurova Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Çukurova Üniversitesi Yumurtalık Meslek Yüksekokulu',
  'Dicle Üniversitesi Atatürk Sağlık Hizmetleri Yüksekokulu',
  'Dicle Üniversitesi Bismil Meslek Yüksekokulu',
  'Dicle Üniversitesi Çermik Meslek Yüksekokulu',
  'Dicle Üniversitesi Çüngüş Mehmet Adıgüzel Meslek Yüksekokulu',
  'Dicle Üniversitesi Diyarbakır Meslek Yüksekokulu',
  'Dicle Üniversitesi Ergani Meslek Yüksekokulu',
  'Dokuz Eylül Üniversitesi Adalet Meslek Yüksekokulu',
  'Dokuz Eylül Üniversitesi İlahiyat Meslek Yüksekokulu',
  'Dokuz Eylül Üniversitesi İzmir Meslek Yüksekokulu',
  'Dokuz Eylül Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Dokuz Eylül Üniversitesi Torbalı Meslek Yüksekokulu',
  'Düzce Üniversitesi Akçakoca Meslek Yüksekokulu',
  'Düzce Üniversitesi Cumayeri Meslek Yüksekokulu',
  'Düzce Üniversitesi Çilimli Meslek Yüksekokulu',
  'Düzce Üniversitesi Düzce Meslek Yüksekokulu',
  'Düzce Üniversitesi Gölyaka Meslek Yüksekokulu',
  'Düzce Üniversitesi Gümüşova Meslek Yüksekokulu',
  'Düzce Üniversitesi Kaynaşlı Meslek Yüksekokulu',
  'Ege Üniversitesi Atatürk Sağlık Hizmetleri Meslek Yüksekokulu',
  'Ege Üniversitesi Bayındır Meslek Yüksekokulu',
  'Ege Üniversitesi Bergama Meslek Yüksekokulu',
  'Ege Üniversitesi Ege Meslek Yüksekokulu',
  'Ege Üniversitesi Emel Akın Meslek Yüksekokulu',
  'Ege Üniversitesi Ödemiş Meslek Yüksekokulu',
  'Ege Üniversitesi Tire Kutsan Meslek Yüksekokulu',
  'Erciyes Üniversitesi Develi Hüseyin Şahin Meslek Yüksekokulu',
  'Erciyes Üniversitesi Halil Bayraktar Sağlık Hizmetleri Meslek Yüksekokulu',
  'Erciyes Üniversitesi İzzet Bayraktar Sosyal Bilimler Meslek Yüksekokulu',
  'Erciyes Üniversitesi Kayseri Meslek Yüksekokulu',
  'Erciyes Üniversitesi Mustafa Çıkrıkçıoğlu Meslek Yüksekokulu',
  'Erciyes Üniversitesi Safiye Çıkrıkçıoğlu Meslek Yüksekokulu',
  'Erzincan Üniversitesi Çayırlı Meslek Yüksekokulu',
  'Erzincan Üniversitesi İlahiyat Meslek Yüksekokulu',
  'Erzincan Üniversitesi Kemah Meslek Yüksekokulu',
  'Erzincan Üniversitesi Kemaliye Hacı Ali Akın Meslek Yüksekokulu',
  'Erzincan Üniversitesi Meslek Yüksekokulu',
  'Erzincan Üniversitesi Refahiye Meslek Yüksekokulu',
  'Erzincan Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Erzincan Üniversitesi Tercan Meslek Yüksekokulu',
  'Erzincan Üniversitesi Turizm Ve Otelcilik Meslek Yüksekokulu',
  'Erzincan Üniversitesi Üzümlü Meslek Yüksekokulu',
  'Eskişehir Osmangazi Üniversitesi Mahmudiye Meslek Yüksekokulu',
  'Eskişehir Osmangazi Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Eskişehir Osmangazi Üniversitesi Sivrihisar Meslek Yüksekokulu',
  'Fatih Üniversitesi Ankara Meslek Yüksekokulu',
  'Fatih Üniversitesi Ankara Sağlık Bilimleri Meslek Yüksekokulu',
  'Fatih Üniversitesi İstanbul Meslek Yüksekokulu',
  'Fırat Üniversitesi Maden Meslek Yüksekokulu',
  'Fırat Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Fırat Üniversitesi Sivrice Meslek Yüksekokulu',
  'Fırat Üniversitesi Sosyal Bilimler Meslek Yüksekokulu',
  'Fırat Üniversitesi Teknik Bilimler Meslek Yüksekokulu',
  'Galatasaray Üniversitesi Meslek Yüksekokulu',
  'Gazi Üniversitesi Ankara Meslek Yüksekokulu',
  'Gazi Üniversitesi Atatürk Meslek Yüksekokulu',
  'Gazi Üniversitesi Beypazarı Teknik Bilimler Meslek Yüksekokulu',
  'Gazi Üniversitesi Gazi Meslek Yüksekokulu',
  'Gazi Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Gazi Üniversitesi Tapu Kadastro Meslek Yüksekokulu',
  'Gazi Üniversitesi Uzaktan Eğitim Meslek Yüksekokulu',
  'Gaziantep Üniversitesi Gaziantep Meslek Yüksekokulu',
  'Gaziantep Üniversitesi Naci Topçuoğlu Meslek Yüksekokulu',
  'Gaziantep Üniversitesi Nizip Meslek Yüksekokulu',
  'Gaziantep Üniversitesi Oğuzeli Meslek Yüksekokulu',
  'Gaziantep Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Gaziantep Üniversitesi Turizm Ve Otelcilik Meslek Yüksekokulu',
  'Gaziosmanpaşa Üniversitesi Almus Meslek Yüksekokulu',
  'Gaziosmanpaşa Üniversitesi Artova Meslek Yüksekokulu',
  'Gaziosmanpaşa Üniversitesi Erbaa Meslek Yüksekokulu',
  'Gaziosmanpaşa Üniversitesi Erbaa Sağlık Hizmetleri Meslek Yüksekokulu',
  'Gaziosmanpaşa Üniversitesi Koyulhisar Meslek Yüksekokulu',
  'Gaziosmanpaşa Üniversitesi Niksar Meslek Yüksekokulu',
  'Gaziosmanpaşa Üniversitesi Pazar Meslek Yüksekokulu',
  'Gaziosmanpaşa Üniversitesi Reşadiye Meslek Yüksekokulu',
  'Gaziosmanpaşa Üniversitesi Tokat Meslek Yüksekokulu',
  'Gaziosmanpaşa Üniversitesi Turhal Meslek Yüksekokulu',
  'Gaziosmanpaşa Üniversitesi Turhal Sağlık Hizmetleri Meslek Yüksekokulu',
  'Gaziosmanpaşa Üniversitesi Zile Meslek Yüksekokulu',
  'Giresun Üniversitesi Alucra Meslek Yüksekokulu',
  'Giresun Üniversitesi Espiye Meslek Yüksekokulu',
  'Giresun Üniversitesi Eynesil Meslek Yüksekokulu',
  'Giresun Üniversitesi Keşap Meslek Yüksekokulu',
  'Giresun Üniversitesi Meslek Yüksekokulu',
  'Giresun Üniversitesi Şebinkarahisar Meslek Yüksekokulu',
  'Giresun Üniversitesi Tirebolu Meslek Yüksekokulu',
  'Hacettepe Üniversitesi Bala Meslek Yüksekokulu',
  'Hacettepe Üniversitesi Hacettepe Meslek Yüksekokulu',
  'Hacettepe Üniversitesi Polatlı Sağlık Hizmetleri Meslek Yüksekokulu',
  'Hacettepe Üniversitesi Polatlı Teknik Bilimler Meslek Yüksekokulu',
  'Hacettepe Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Hacettepe Üniversitesi Sosyal Bilimler Meslek Yüksekokulu',
  'Harran Üniversitesi Akçakale Meslek Yüksekokulu',
  'Harran Üniversitesi Birecik Meslek Yüksekokulu',
  'Harran Üniversitesi Bozova Meslek Yüksekokulu',
  'Harran Üniversitesi Ceylanpınar Meslek Yüksekokulu',
  'Harran Üniversitesi Hilvan Meslek Yüksekokulu',
  'Harran Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Harran Üniversitesi Siverek Meslek Yüksekokulu',
  'Harran Üniversitesi Suruç Meslek Yüksekokulu',
  'Harran Üniversitesi Şanlıurfa Meslek Yüksekokulu',
  'Harran Üniversitesi Viranşehir Meslek Yüksekokulu',
  'Hitit Üniversitesi Meslek Yüksekokulu',
  'Hitit Üniversitesi Osmancık Meslek Yüksekokulu',
  'Hitit Üniversitesi Sungurlu Meslek Yüksekokulu',
  'İnönü Üniversitesi Akçadağ Meslek Yüksekokulu',
  'İnönü Üniversitesi Arapgir Meslek Yüksekokulu',
  'İnönü Üniversitesi Battalgazi Meslek Yüksekokulu',
  'İnönü Üniversitesi Hekimhan Meslek Yüksekokulu',
  'İnönü Üniversitesi Kale Meslek Yüksekokulu',
  'İnönü Üniversitesi Malatya Meslek Yüksekokulu',
  'İnönü Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'İnönü Üniversitesi Sürgü Meslek Yüksekokulu',
  'İnönü Üniversitesi Yakınca Meslek Yüksekokulu',
  'İstanbul Arel Üniversitesi Anadolu Bil Meslek Yüksekokulu',
  'İstanbul Arel Üniversitesi Meslek Yüksekokulu',
  'İstanbul Bilim Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'İstanbul Kültür Üniversitesi İşletmecilik Meslek Yüksekokulu',
  'İstanbul Kültür Üniversitesi Teknik Bilimler Meslek Yüksekokulu',
  'İstanbul Teknik Üniversitesi Meslek Yüksekokulu',
  'İstanbul Üniversitesi Adalet Meslek Yüksekokulu',
  'İstanbul Üniversitesi Ormancılık Meslek Yüksekokulu',
  'İstanbul Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'İstanbul Üniversitesi Sapanca Su Ürünleri Meslek Yüksekokulu',
  'İstanbul Üniversitesi Sosyal Bilimler Meslek Yüksekokulu',
  'İstanbul Üniversitesi Teknik Bilimler Meslek Yüksekokulu',
  'İstanbul Üniversitesi Veteriner Fakültesi Meslek Yüksekokulu',
  'İzmir Ekonomi Üniversitesi Meslek Yüksekokulu',
  'Kadir Has Üniversitesi Sosyal Bilimler Meslek Yüksekokulu',
  'Kadir Has Üniversitesi Teknik Bilimler Meslek Yüksekokulu',
  'Kafkas Üniversitesi Atatürk Sağlık Hizmetleri Meslek Yüksekokulu',
  'Kafkas Üniversitesi Kağızman Meslek Yüksekokulu',
  'Kafkas Üniversitesi Kars Meslek Yüksekokulu',
  'Kafkas Üniversitesi Sarıkamış Meslek Yüksekokulu',
  'Kafkas Üniversitesi Sosyal Bilimler Meslek Yüksekokulu',
  'Kahramanmaraş Sütçü İmam Üniversitesi Afşin Meslek Yüksekokulu',
  'Kahramanmaraş Sütçü İmam Üniversitesi Andırın Meslek Yüksekokulu',
  'Kahramanmaraş Sütçü İmam Üniversitesi Elbistan Meslek Yüksekokulu',
  'Kahramanmaraş Sütçü İmam Üniversitesi Göksun Meslek Yüksekokulu',
  'Kahramanmaraş Sütçü İmam Üniversitesi Islahiye Meslek Yüksekokulu',
  'Kahramanmaraş Sütçü İmam Üniversitesi Kahramanmaraş Meslek Yüksekokulu',
  'Kahramanmaraş Sütçü İmam Üniversitesi Pazarcık Meslek Yüksekokulu',
  'Kahramanmaraş Sütçü İmam Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Karabük Üniversitesi Meslek Yüksekokulu',
  'Karabük Üniversitesi Safranbolu Meslek Yüksekokulu',
  'Karamanoğlu Mehmetbey Üniversitesi Ermenek Meslek Yüksekokulu',
  'Karamanoğlu Mehmetbey Üniversitesi Kazım Karabekir Meslek Yüksekokulu',
  'Karamanoğlu Mehmetbey Üniversitesi Meslek Yüksekokulu',
  'Kastamonu Üniversitesi Cide Rıfat Ilgaz Meslek Yüksekokulu',
  'Kastamonu Üniversitesi İnebolu Meslek Yüksekokulu',
  'Kastamonu Üniversitesi Kastamonu Meslek Yüksekokulu',
  'Kırıkkale Üniversitesi Adalet Meslek Yüksekokulu',
  'Kırıkkale Üniversitesi Delice Meslek Yüksekokulu',
  'Kırıkkale Üniversitesi Hacılar Hüseyin Aytemiz Meslek Yüksekokulu',
  'Kırıkkale Üniversitesi Keskin Meslek Yüksekokulu',
  'Kırıkkale Üniversitesi Kırıkkale Meslek Yüksekokulu',
  'Kırklareli Üniversitesi Babaeski Meslek Yüksekokulu',
  'Kırklareli Üniversitesi Lüleburgaz Kepirtepe Meslek Yüksekokulu',
  'Kırklareli Üniversitesi Pınarhisar Meslek Yüksekokulu',
  'Kırklareli Üniversitesi Sosyal Bilimler Meslek Yüksekokulu',
  'Kırklareli Üniversitesi Teknik Bilimler Meslek Yüksekokulu',
  'Kırklareli Üniversitesi Vize Meslek Yüksekokulu',
  'Kilis 7 Aralık Üniversitesi Kilis Meslek Yüksekokulu',
  'Kilis 7 Aralık Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Kocaeli Üniversitesi Ali Rıza Veziroğlu Meslek Yüksekokulu',
  'Kocaeli Üniversitesi Arslanbey Meslek Yüksekokulu',
  'Kocaeli Üniversitesi Asım Kocabıyık Meslek Yüksekokulu',
  'Kocaeli Üniversitesi Değirmendere Ali Özbay Meslek Yüksekokulu',
  'Kocaeli Üniversitesi Derbent Meslek Yüksekokulu',
  'Kocaeli Üniversitesi Gazanfer Bilge Meslek Yüksekokulu',
  'Kocaeli Üniversitesi Gebze Meslek Yüksekokulu',
  'Kocaeli Üniversitesi Gölcük Meslek Yüksekokulu',
  'Kocaeli Üniversitesi Hereke Ömer İsmet Uzunyol Meslek Yüksekokulu',
  'Kocaeli Üniversitesi İhsaniye Meslek Yüksekokulu',
  'Kocaeli Üniversitesi İzmit Meslek Yüksekokulu',
  'Kocaeli Üniversitesi Kandıra Meslek Yüksekokulu',
  'Kocaeli Üniversitesi Karamürsel Meslek Yüksekokulu',
  'Kocaeli Üniversitesi Kartepe Meslek Yüksekokulu',
  'Kocaeli Üniversitesi Kocaeli Meslek Yüksekokulu',
  'Kocaeli Üniversitesi Kocaeli Sağlık Meslek Yüksekokulu',
  'Kocaeli Üniversitesi Köseköy Meslek Yüksekokulu',
  'Kocaeli Üniversitesi Uzunçiftlik Nuh Çimento Meslek Yüksekokulu',
  'Kocaeli Üniversitesi Yahya Kaptan Meslek Yüksekokulu',
  'Maltepe Üniversitesi Meslek Yüksekokulu',
  'Marmara Üniversitesi İlahiyat Meslek Yüksekokulu',
  'Marmara Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Marmara Üniversitesi Sosyal Bilimler Meslek Yüksekokulu',
  'Marmara Üniversitesi Teknik Bilimler Meslek Yüksekokulu',
  'Mehmet Akif Ersoy Üniversitesi Ağlasun Meslek Yüksekokulu',
  'Mehmet Akif Ersoy Üniversitesi Bucak Emin Gülmez Teknik Bilimler Meslek Yüksekokulu',
  'Mehmet Akif Ersoy Üniversitesi Bucak Hikmet Tolunay Meslek Yüksekokulu',
  'Mehmet Akif Ersoy Üniversitesi Gölhisar Meslek Yüksekokulu',
  'Mehmet Akif Ersoy Üniversitesi Meslek Yüksekokulu',
  'Mersin Üniversitesi Anamur Meslek Yüksekokulu',
  'Mersin Üniversitesi Aydıncık Meslek Yüksekokulu',
  'Mersin Üniversitesi Deniz Ve Ticaret Meslek Yüksekokulu',
  'Mersin Üniversitesi Erdemli Meslek Yüksekokulu',
  'Mersin Üniversitesi Gülnar Meslek Yüksekokulu',
  'Mersin Üniversitesi Mersin Meslek Yüksekokulu (Uzaktan Eğitim)',
  'Mersin Üniversitesi Mut Meslek Yüksekokulu',
  'Mersin Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Mersin Üniversitesi Silifke Meslek Yüksekokulu',
  'Mersin Üniversitesi Sosyal Bilimler Meslek Yüksekokulu',
  'Mersin Üniversitesi Tarsus Meslek Yüksekokulu',
  'Mersin Üniversitesi Teknik Bilimler Meslek Yüksekokulu',
  'Msgsü Meslek Yüksekokulu',
  'Muğla Üniversitesi Dalaman Meslek Yüksekokulu',
  'Muğla Üniversitesi Datça Kazım Yılmaz Meslek Yüksekokulu',
  'Muğla Üniversitesi Fethiye Ali Sıtkı Mefharet Koçman Meslek Yüksekokulu',
  'Muğla Üniversitesi Milas Sıtkı Koçman Meslek Yüksekokulu',
  'Muğla Üniversitesi Muğla Meslek Yüksekokulu',
  'Muğla Üniversitesi Ortaca Meslek Yüksekokulu',
  'Muğla Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Muğla Üniversitesi Ula Ali Koçman Meslek Yüksekokulu',
  'Muğla Üniversitesi Yatağan Meslek Yüksekokulu',
  'Mustafa Kemal Üniversitesi Altınözü Meslek Yüksekokulu',
  'Mustafa Kemal Üniversitesi Antakya Meslek Yüksekokulu',
  'Mustafa Kemal Üniversitesi Belen Meslek Yüksekokulu',
  'Mustafa Kemal Üniversitesi Dörtyol Meslek Yüksekokulu',
  'Mustafa Kemal Üniversitesi Harbiye Meslek Yüksekokulu',
  'Mustafa Kemal Üniversitesi Hassa Meslek Yüksekokulu',
  'Mustafa Kemal Üniversitesi Hatay Sağlık Hizmetleri Meslek Yüksekokulu',
  'Mustafa Kemal Üniversitesi İskenderun Meslek Yüksekokulu',
  'Mustafa Kemal Üniversitesi Kırıkhan Meslek Yüksekokulu',
  'Mustafa Kemal Üniversitesi Pirinçlik Meslek Yüksekokulu',
  'Mustafa Kemal Üniversitesi Reyhanlı Meslek Yüksekokulu',
  'Mustafa Kemal Üniversitesi Samandağı Meslek Yüksekokulu',
  'Mustafa Kemal Üniversitesi Yayladağı Meslek Yüksekokulu',
  'Namık Kemal Üniversitesi Çerkezköy Meslek Yüksekokulu',
  'Namık Kemal Üniversitesi Çorlu Meslek Yüksekokulu',
  'Namık Kemal Üniversitesi Hayrabolu Meslek Yüksekokulu',
  'Namık Kemal Üniversitesi Malkara Meslek Yüksekokulu',
  'Namık Kemal Üniversitesi Marmara Ereğlisi Meslek Yüksekokulu',
  'Namık Kemal Üniversitesi Muratlı Meslek Yüksekokulu',
  'Namık Kemal Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Namık Kemal Üniversitesi Saray Meslek Yüksekokulu',
  'Namık Kemal Üniversitesi Sosyal Bilimler Meslek Yüksekokulu',
  'Namık Kemal Üniversitesi Şarköy Meslek Yüksekokulu',
  'Namık Kemal Üniversitesi Teknik Bilimler Meslek Yüksekokulu',
  'Nevşehir Üniversitesi Avanos Meslek Yüksekokulu',
  'Nevşehir Üniversitesi Gülşehir Meslek Yüksekokulu',
  'Nevşehir Üniversitesi Hacıbektaş Veli Meslek Yüksekokulu',
  'Nevşehir Üniversitesi Nevşehir Meslek Yüksekokulu',
  'Nevşehir Üniversitesi Ürgüp Sebahat Ve Erol Toksöz Meslek Yüksekokulu',
  'Niğde Üniversitesi Bor Halil Zöhre Ataman Meslek Yüksekokulu',
  'Niğde Üniversitesi Bor Meslek Yüksekokulu',
  'Niğde Üniversitesi Niğde Meslek Yüksekokulu',
  'Niğde Üniversitesi Ulukışla Meslek Yüksekokulu',
  'Niğde Üniversitesi Zübeyde Hanım Sağlık Hizmetleri Meslek Yüksekokulu',
  'Okan Üniversitesi Meslek Yüksekokulu',
  'Ondokuz Mayıs Üniversitesi Alaçam Meslek Yüksekokulu',
  'Ondokuz Mayıs Üniversitesi Bafra Meslek Yüksekokulu',
  'Ondokuz Mayıs Üniversitesi Çarşamba Ticaret Borsası Meslek Yüksekokulu',
  'Ondokuz Mayıs Üniversitesi Havza Meslek Yüksekokulu',
  'Ondokuz Mayıs Üniversitesi Kavak Meslek Yüksekokulu',
  'Ondokuz Mayıs Üniversitesi Samsun Meslek Yüksekokulu',
  'Ondokuz Mayıs Üniversitesi Terme Meslek Yüksekokulu',
  'Ondokuz Mayıs Üniversitesi Vezirköprü Meslek Yüksekokulu',
  'Ordu Üniversitesi Akkuş Meslek Yüksekokulu',
  'Ordu Üniversitesi Fatsa Meslek Yüksekokulu',
  'Ordu Üniversitesi Meslek Yüksekokulu',
  'Ordu Üniversitesi Mesudiye Meslek Yüksekokulu',
  'Ordu Üniversitesi Ulubey Meslek Yüksekokulu',
  'Ordu Üniversitesi Ünye Meslek Yüksekokulu',
  'Orta Doğu Teknik Üniversitesi Meslek Yüksekokulu',
  'Osmaniye Korkut Ata Üniversitesi Bahçe Meslek Yüksekokulu',
  'Osmaniye Korkut Ata Üniversitesi Düziçi Meslek Yüksekokulu',
  'Osmaniye Korkut Ata Üniversitesi Erzin Meslek Yüksekokulu',
  'Osmaniye Korkut Ata Üniversitesi Kadirli Meslek Yüksekokulu',
  'Osmaniye Korkut Ata Üniversitesi Osmaniye Meslek Yüksekokulu',
  'Pamukkale Üniversitesi Bekilli Meslek Yüksekokulu',
  'Pamukkale Üniversitesi Buldan Meslek Yüksekokulu',
  'Pamukkale Üniversitesi Çivril Meslek Yüksekokulu',
  'Pamukkale Üniversitesi Denizli Meslek Yüksekokulu',
  'Pamukkale Üniversitesi Denizli Sağlık Hizmetleri Meslek Yüksekokulu',
  'Pamukkale Üniversitesi Honaz Meslek Yüksekokulu',
  'Rize Üniversitesi Ardeşen Meslek Yüksekokulu',
  'Rize Üniversitesi Fındıklı Meslek Yüksekokulu',
  'Rize Üniversitesi Pazar Meslek Yüksekokulu',
  'Rize Üniversitesi Rize Meslek Yüksekokulu',
  'S.Ü. Hukuk Fakültesi Adalet Meslek Yüksekokulu',
  'Sakarya Üniversitesi Adapazarı Meslek Yüksekokulu',
  'Sakarya Üniversitesi Akyazı Meslek Yüksekokulu',
  'Sakarya Üniversitesi Ali Fuat Cebesoy Meslek Yüksekokulu',
  'Sakarya Üniversitesi Ferizli Meslek Yüksekokulu',
  'Sakarya Üniversitesi Geyve Meslek Yüksekokulu',
  'Sakarya Üniversitesi Hendek Meslek Yüksekokulu',
  'Sakarya Üniversitesi Karasu Meslek Yüksekokulu',
  'Sakarya Üniversitesi Kaynarca Seyfettin Selim Meslek Yüksekokulu',
  'Sakarya Üniversitesi Pamukova Meslek Yüksekokulu',
  'Sakarya Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Sakarya Üniversitesi Sakarya Meslek Yüksekokulu',
  'Sakarya Üniversitesi Sapanca Meslek Yüksekokulu',
  'Sdü Aksu Mehmet Süreyya Demiraslan Meslek Yüksekokulu',
  'Sdü Isparta Sağlık Hizmetleri Meslek Yüksekokulu',
  'Sdü Sütçüler Prof.Dr.Hasan Gürbüz Meslek Yüksekokulu',
  'Sdü Uluborlu Selahattin Karasoy Meslek Yüksekokulu',
  'Selçuk Üniversitesi Akören Ali Rıza Ercan Meslek Yüksekokulu',
  'Selçuk Üniversitesi Akşehir Meslek Yüksekokulu',
  'Selçuk Üniversitesi Beyşehir Ali Akkanat Meslek Yüksekokulu',
  'Selçuk Üniversitesi Bozkır Meslek Yüksekokulu',
  'Selçuk Üniversitesi Cihanbeyli Meslek Yüksekokulu',
  'Selçuk Üniversitesi Çumra Meslek Yüksekokulu',
  'Selçuk Üniversitesi Doğanhisar Meslek Yüksekokulu',
  'Selçuk Üniversitesi Güneysınır Meslek Yüksekokulu',
  'Selçuk Üniversitesi Hadim Meslek Yüksekokulu',
  'Selçuk Üniversitesi Huğlu Meslek Yüksekokulu',
  'Selçuk Üniversitesi Ilgın Meslek Yüksekokulu',
  'Selçuk Üniversitesi Kadınhanı Faik İçil Meslek Yüksekokulu',
  'Selçuk Üniversitesi Karapınar Aydoğanlar Meslek Yüksekokulu',
  'Selçuk Üniversitesi Konya Ereğli Kemal Akman Meslek Yüksekokulu',
  'Selçuk Üniversitesi Kulu Meslek Yüksekokulu',
  'Selçuk Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Selçuk Üniversitesi Sarayönü Meslek Yüksekokulu',
  'Selçuk Üniversitesi Seydişehir Meslek Yüksekokulu',
  'Selçuk Üniversitesi Silifke - Taşucu Meslek Yüksekokulu',
  'Selçuk Üniversitesi Sosyal Bilimler Meslek Yüksekokulu',
  'Selçuk Üniversitesi Teknik Bilimler Meslek Yüksekokulu',
  'Sinop Üniversitesi Ayancık Meslek Yüksekokulu',
  'Sinop Üniversitesi Boyabat Meslek Yüksekokulu',
  'Sinop Üniversitesi Gerze Meslek Yüksekokulu',
  'Sinop Üniversitesi Meslek Yüksekokulu',
  'Süleyman Demirel Üniversitesi Atabey Meslek Yüksekokulu',
  'Süleyman Demirel Üniversitesi Eğirdir Meslek Yüksekokulu',
  'Süleyman Demirel Üniversitesi Gelendost Meslek Yüksekokulu',
  'Süleyman Demirel Üniversitesi Gönen Meslek Yüksekokulu',
  'Süleyman Demirel Üniversitesi Isparta Meslek Yüksekokulu',
  'Süleyman Demirel Üniversitesi Keçiborlu Meslek Yüksekokulu',
  'Süleyman Demirel Üniversitesi Senirkent Meslek Yüksekokulu',
  'Süleyman Demirel Üniversitesi Şarkikaraağaç Meslek Yüksekokulu',
  'Süleyman Demirel Üniversitesi Teknik Bilimler Meslek Yüksekokulu',
  'Süleyman Demirel Üniversitesi Uzaktan Eğitim Meslek Yüksekokulu',
  'Süleyman Demirel Üniversitesi Yalvaç Meslek Yüksekokulu',
  'Süleyman Demirel Üniversitesi Yalvaç Teknik Bilimler Meslek Yüksekokulu',
  'Süleyman Demirel Üniversitesi Yenişarbademli Meslek Yüksekokulu',
  'Şırnak Üniversitesi Cizre Meslek Yüksekokulu',
  'Şırnak Üniversitesi Şırnak Meslek Yüksekokulu',
  'Trakya Üniversitesi Arda Meslek Yüksekokulu',
  'Trakya Üniversitesi Edirne Sosyal Bilimler Meslek Yüksekokulu',
  'Trakya Üniversitesi Edirne Teknik Bilimler Meslek Yüksekokulu',
  'Trakya Üniversitesi Havsa Meslek Yüksekokulu',
  'Trakya Üniversitesi İpsala Meslek Yüksekokulu',
  'Trakya Üniversitesi Keşan Meslek Yüksekokulu',
  'Trakya Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Trakya Üniversitesi Tunca Meslek Yüksekokulu',
  'Trakya Üniversitesi Uzunköprü Meslek Yüksekokulu',
  'Ufuk Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Uludağ Üniversitesi Gemlik Asım Kocabıyık Meslek Yüksekokulu',
  'Uludağ Üniversitesi Harmancık Meslek Yüksekokulu',
  'Uludağ Üniversitesi İnegöl Meslek Yüksekokulu',
  'Uludağ Üniversitesi İznik Meslek Yüksekokulu',
  'Uludağ Üniversitesi Karacabey Meslek Yüksekokulu',
  'Uludağ Üniversitesi Keles Meslek Yüksekokulu',
  'Uludağ Üniversitesi M.Kemalpaşa Meslek Yüksekokulu',
  'Uludağ Üniversitesi Mennan Pasinli Meslek Yüksekokulu',
  'Uludağ Üniversitesi Orhangazi Meslek Yüksekokulu',
  'Uludağ Üniversitesi Orheli Meslek Yüksekokulu',
  'Uludağ Üniversitesi Sağlık Hizmetleri Meslek Yüksekokulu',
  'Uludağ Üniversitesi Sosyal Bilimler Meslek Yüksekokulu',
  'Uludağ Üniversitesi Teknik Bilimler Meslek Yüksekokulu',
  'Uludağ Üniversitesi Yenişehir İbrahim Orhan Meslek Yüksekokulu',
  'Yaşar Üniversitesi Meslek Yüksekokulu',
  'Yıldız Teknik Üniversitesi Meslek Yüksekokulu',
  'Yıldız Teknik Üniversitesi Milli Saraylar Ve Tarihi Yapılar Meslek Yüksekokulu',
  'Zonguldak Karaelmas Üniversitesi Alaplı Meslek Yüksekokulu',
  'Zonguldak Karaelmas Üniversitesi Çaycuma Meslek Yüksekokulu',
  'Zonguldak Karaelmas Üniversitesi Devrek Meslek Yüksekokulu',
  'Zonguldak Karaelmas Üniversitesi Gökçebey Mithat-Mehmet Çanakçı Meslek Yüksekokulu',
  'Zonguldak Karaelmas Üniversitesi Zonguldak Meslek Yüksekokulu',
  'Zonguldak Karaelmas Üniversitesi Zonguldak Sağlık Hizmetleri Meslek Yüksekokulu',
];

// Kaynak: YÖK — https://github.com/0xseck/Turkish-Universities-and-Faculties-in-Json
export const UNIVERSITELER: string[] = [
  'Abdullah Gül Üniversitesi',
  'Acıbadem Mehmet Ali Aydınlar Üniversitesi',
  'Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi',
  'Adıyaman Üniversitesi',
  'Afyon Kocatepe Üniversitesi',
  'Afyonkarahisar Sağlık Bilimleri Üniversitesi',
  'Ağrı İbrahim Çeçen Üniversitesi',
  'Akdeniz Üniversitesi',
  'Aksaray Üniversitesi',
  'Alanya Alaaddin Keykubat Üniversitesi',
  'Alanya Hamdullah Emin Paşa Üniversitesi',
  'Altınbaş Üniversitesi',
  'Amasya Üniversitesi',
  'Anadolu Üniversitesi',
  'Ankara Hacı Bayram Veli Üniversitesi',
  'Ankara Medipol Üniversitesi',
  'Ankara Sosyal Bilimler Üniversitesi',
  'Ankara Üniversitesi',
  'Ankara Yıldırım Beyazıt Üniversitesi',
  'Antalya Akev Üniversitesi',
  'Antalya Bilim Üniversitesi',
  'Ardahan Üniversitesi',
  'Artvin Çoruh Üniversitesi',
  'Atatürk Üniversitesi',
  'Atılım Üniversitesi',
  'Avrasya Üniversitesi',
  'Aydın Adnan Menderes Üniversitesi',
  'Bahçeşehir Üniversitesi',
  'Balıkesir Üniversitesi',
  'Bandırma Onyedi Eylül Üniversitesi',
  'Bartın Üniversitesi',
  'Başkent Üniversitesi',
  'Batman Üniversitesi',
  'Bayburt Üniversitesi',
  'Beykent Üniversitesi',
  'Beykoz Üniversitesi',
  'Bezm-i Âlem Vakıf Üniversitesi',
  'Bilecik Şeyh Edebali Üniversitesi',
  'Bingöl Üniversitesi',
  'Biruni Üniversitesi',
  'Bitlis Eren Üniversitesi',
  'Boğaziçi Üniversitesi',
  'Bolu Abant İzzet Baysal Üniversitesi',
  'Burdur Mehmet Akif Ersoy Üniversitesi',
  'Bursa Teknik Üniversitesi',
  'Bursa Uludağ Üniversitesi',
  'Çağ Üniversitesi',
  'Çanakkale Onsekiz Mart Üniversitesi',
  'Çankaya Üniversitesi',
  'Çankırı Karatekin Üniversitesi',
  'Çukurova Üniversitesi',
  'Demiroğlu Bilim Üniversitesi',
  'Dicle Üniversitesi',
  'Doğuş Üniversitesi',
  'Dokuz Eylül Üniversitesi',
  'Düzce Üniversitesi',
  'Ege Üniversitesi',
  'Erciyes Üniversitesi',
  'Erzincan Binali Yıldırım Üniversitesi',
  'Erzurum Teknik Üniversitesi',
  'Eskişehir Osmangazi Üniversitesi',
  'Eskişehir Teknik Üniversitesi',
  'Fatih Sultan Mehmet Vakıf Üniversitesi',
  'Fenerbahçe Üniversitesi',
  'Fırat Üniversitesi',
  'Galatasaray Üniversitesi',
  'Gazi Üniversitesi',
  'Gaziantep İslam Bilim ve Teknoloji Üniversitesi',
  'Gaziantep Üniversitesi',
  'Gebze Teknik Üniversitesi',
  'Giresun Üniversitesi',
  'Gümüşhane Üniversitesi',
  'Hacettepe Üniversitesi',
  'Hakkari Üniversitesi',
  'Haliç Üniversitesi',
  'Harran Üniversitesi',
  'Hasan Kalyoncu Üniversitesi',
  'Hitit Üniversitesi',
  'Ibn Haldun Üniversitesi',
  'Iğdır Üniversitesi',
  'Isparta Uygulamalı Bilimler Üniversitesi',
  'İnönü Üniversitesi',
  'İskenderun Teknik Üniversitesi',
  'İstanbul 29 Mayıs Üniversitesi',
  'İstanbul Arel Üniversitesi',
  'İstanbul Aydın Üniversitesi',
  'İstanbul Ayvansaray Üniversitesi',
  'İstanbul Bilgi Üniversitesi',
  'İstanbul Esenyurt Üniversitesi',
  'İstanbul Gedik Üniversitesi',
  'İstanbul Gelişim Üniversitesi',
  'İstanbul Kent Üniversitesi',
  'İstanbul Kültür Üniversitesi',
  'İstanbul Medeniyet Üniversitesi',
  'İstanbul Medipol Üniversitesi',
  'İstanbul Okan Üniversitesi',
  'İstanbul Rumeli Üniversitesi',
  'İstanbul Sabahattin Zaim Üniversitesi',
  'İstanbul Teknik Üniversitesi',
  'İstanbul Ticaret Üniversitesi',
  'İstanbul Üniversitesi',
  'İstanbul Üniversitesi-Cerrahpaşa',
  'İstanbul Yeni Yüzyıl Üniversitesi',
  'İstinye Üniversitesi',
  'İzmir Bakırçay Üniversitesi',
  'İzmir Demokrasi Üniversitesi',
  'İzmir Ekonomi Üniversitesi',
  'İzmir Katip Çelebi Üniversitesi',
  'İzmir Yüksek Teknoloji Enstitüsü',
  'İhsan Doğramacı Bilkent Üniversitesi',
  'Kafkas Üniversitesi',
  'Kahramanmaraş İstiklal Üniversitesi',
  'Kahramanmaraş Sütçü İmam Üniversitesi',
  'Kadir Has Üniversitesi',
  'Kapadokya Üniversitesi',
  'Karabük Üniversitesi',
  'Karadeniz Teknik Üniversitesi',
  'Karamanoğlu Mehmetbey Üniversitesi',
  'Kastamonu Üniversitesi',
  'Kayseri Üniversitesi',
  'Kilis 7 Aralık Üniversitesi',
  'Kırıkkale Üniversitesi',
  'Kırklareli Üniversitesi',
  'Kırşehir Ahi Evran Üniversitesi',
  'Koç Üniversitesi',
  'Kocaeli Üniversitesi',
  'Konya Gıda ve Tarım Üniversitesi',
  'Konya Teknik Üniversitesi',
  'KTO Karatay Üniversitesi',
  'Kütahya Dumlupınar Üniversitesi',
  'Kütahya Sağlık Bilimleri Üniversitesi',
  'Lokman Hekim Üniversitesi',
  'Malatya Turgut Özal Üniversitesi',
  'Maltepe Üniversitesi',
  'Manisa Celâl Bayar Üniversitesi',
  'Mardin Artuklu Üniversitesi',
  'Marmara Üniversitesi',
  'MEF Üniversitesi',
  'Mersin Üniversitesi',
  'Mimar Sinan Güzel Sanatlar Üniversitesi',
  'Muğla Sıtkı Koçman Üniversitesi',
  'Munzur Üniversitesi',
  'Muş Alparslan Üniversitesi',
  'Necmettin Erbakan Üniversitesi',
  'Nevşehir Hacı Bektaş Veli Üniversitesi',
  'Niğde Ömer Halisdemir Üniversitesi',
  'Nişantaşı Üniversitesi',
  'Nuh Naci Yazgan Üniversitesi',
  'Ondokuz Mayıs Üniversitesi',
  'Ordu Üniversitesi',
  'Orta Doğu Teknik Üniversitesi',
  'Osmaniye Korkut Ata Üniversitesi',
  'Ostim Teknik Üniversitesi',
  'Özyeğin Üniversitesi',
  'Pamukkale Üniversitesi',
  'Piri Reis Üniversitesi',
  'Recep Tayyip Erdoğan Üniversitesi',
  'Sabancı Üniversitesi',
  'Sağlık Bilimleri Üniversitesi',
  'Sakarya Uygulamalı Bilimler Üniversitesi',
  'Sakarya Üniversitesi',
  'Samsun Üniversitesi',
  'Sanko Üniversitesi',
  'Selçuk Üniversitesi',
  'Siirt Üniversitesi',
  'Sinop Üniversitesi',
  'Sivas Cumhuriyet Üniversitesi',
  'Şırnak Üniversitesi',
  'Tarsus Üniversitesi',
  'TED Üniversitesi',
  'Tekirdağ Namık Kemal Üniversitesi',
  'TOBB Ekonomi ve Teknoloji Üniversitesi',
  'Tokat Gaziosmanpaşa Üniversitesi',
  'Toros Üniversitesi',
  'Trabzon Üniversitesi',
  'Trakya Üniversitesi',
  'Tunceli Munzur Üniversitesi',
  'Türk-Alman Üniversitesi',
  'Türk Hava Kurumu Üniversitesi',
  'Ufuk Üniversitesi',
  'Uşak Üniversitesi',
  'Üsküdar Üniversitesi',
  'Van Yüzüncü Yıl Üniversitesi',
  'Yalova Üniversitesi',
  'Yaşar Üniversitesi',
  'Yeditepe Üniversitesi',
  'Yıldız Teknik Üniversitesi',
  'Yozgat Bozok Üniversitesi',
  'Yüksek İhtisas Üniversitesi',
  'Zonguldak Bülent Ecevit Üniversitesi',
  'Hatay Mustafa Kemal Üniversitesi',
];
